version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.64
    - 0.12.70
  - dependency-name: symfony/console
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: symfony/yaml
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.1.10
  - dependency-name: symfony/twig-bundle
    versions:
    - 5.1.10
