language: php
sudo: false

php:
  - 7.3

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --dev
  - pip install --user awscli
  - pip install --user aws-sam-cli

script:
  - envsubst < .env.dist > .env
  - cat .env
