language: php
sudo: false

php:
  - 7.3

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --dev
  - pip install --user awscli
  - pip install --user aws-sam-cli

deploy:
  provider: script
  script: envsubst < .env.travis > .env && sam package --output-template-file .stack.yaml --s3-bucket estcelafindelajournee --region us-east-1 && sam deploy --template-file .stack.yaml --capabilities CAPABILITY_IAM --stack-name estcelafindelajournee --region us-east-1
  skip_cleanup: true
  on:
    tags: true
    branch: master
