language: php
sudo: false

php:
  - 7.3

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

before_install:
  - composer self-update

install:
  - pip install --user awscli
  - pip install --user aws-sam-cli

before_script:
  - composer install --no-interaction --dev
  - envsubst < .env.travis > .env
  - php bin/console cache:warmup

script:
  - php bin/phpunit
  - vendor/bin/phpstan analyse -l max -c phpstan.neon src --no-interaction --no-progress

before_deploy:
  - rm -rf .env
  - rm -rf vendor/
  - rm -rf bin/.phpunit
  - rm -rf bin/phpunit
  - rm -rf var/*
  - composer install --no-interaction --no-dev
  - php bin/console cache:warmup --env=prod
  - envsubst < .env.travis > .env

deploy:
  provider: script
  script: sam package --output-template-file .stack.yaml --s3-bucket estcelafindelajournee --region us-east-1 && sam deploy --template-file .stack.yaml --capabilities CAPABILITY_IAM --stack-name estcelafindelajournee --region us-east-1
  skip_cleanup: true
  on:
    tags: true
    branch: master
