language: php

php:
  - 7.4

env:
  - NODE_RELEASE=12.x

install:
  - composer self-update

before_script:
  - composer install --no-interaction --dev
  - envsubst < .env.travis > .env

script:
  - php bin/phpunit
  - vendor/bin/phpstan analyse -l 1 -c phpstan.neon src --no-interaction --no-progress

before_deploy:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g serverless
  - rm -rf .env
  - rm -rf vendor/
  - rm -rf bin/.phpunit
  - rm -rf bin/phpunit
  - rm -rf var/*
  - composer install --no-interaction --no-dev
  - php bin/console cache:warmup --env=prod
  - envsubst < .env.travis > .env

deploy:
  provider: script
  script: serverless deploy
  skip_cleanup: true
  on:
    branch: master
