language: php
sudo: false

php:
  - 7.4

install:
  - composer self-update

before_script:
  - composer install --no-interaction --dev
  - envsubst < .env.travis > .env

script:
  - php bin/phpunit
  - vendor/bin/phpstan analyse -l 1 -c phpstan.neon src --no-interaction --no-progress

before_deploy:
  - npm install -g serverless
  - rm -rf .env
  - rm -rf vendor/
  - rm -rf bin/.phpunit
  - rm -rf bin/phpunit
  - rm -rf var/*
  - composer install --no-interaction --no-dev
  - php bin/console cache:warmup --env=prod
  - envsubst < .env.travis > .env

deploy:
  provider: script
  script: serverless deploy
  skip_cleanup: true
  on:
    tags: true
    branch: master
