matrix:
  include:
    - language: php
      php:
        - 7.4

      install:
        - composer self-update

      before_script:
        - composer install --no-interaction --dev
        - envsubst < .env.travis > .env

      script:
        - php bin/phpunit
        - vendor/bin/phpstan analyse -l 1 -c phpstan.neon src --no-interaction --no-progress

      deploy:
        provider: script
        script:
          - rm -rf .env
          - rm -rf vendor/
          - rm -rf bin/.phpunit
          - rm -rf bin/phpunit
          - rm -rf var/*
          - composer install --no-interaction --no-dev
          - php bin/console cache:warmup --env=prod
          - envsubst < .env.travis > .env
        on:
          branch: master

    - language: node.js
      node_js: "12.0"

      install:
        - npm install -g serverless
      deploy:
        provider: script
        script: serverless deploy
        skip_cleanup: true
        on:
          branch: master
