language: php
sudo: false

php:
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --dev
  - ./bin/phpunit install

jobs:
  include:
    - name: Tests
      script:
        - phpunit
