language: php
sudo: false

php:
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --dev

jobs:
  include:
    - name: Deploy
      script:
        - phpunit
        - pip install --user awscli
        - pip install --user aws-sam-cli
      if: branch = master AND fork = false