services:
    app:
        image: bref/php-84-fpm-dev:2
        ports: [ '8000:8000' ]
        volumes:
            - .:/var/task
            - ./var:/var/task/var
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
