services:
    app:
        image: bref/php-85-dev:3
        ports: [ '8000:8000' ]
        volumes:
            - .:/var/task
            - ./var:/var/task/var
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
            BREF_RUNTIME: fpm
