service: app

provider:
  name: aws
  region: eu-west-1
  runtime: provided.al2
  stage: prod
  environment:
    APP_ENV: 'prod'
    APP_SECRET: ${ssm:/estcelafindelajournee/secret}

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  api:
    handler: public/index.php
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'

constructs:
  website:
    type: server-side-website
    assets:
      '/bundles/*': public/bundles
      '/css/*': public/css
      '/favicon.ico': public/favicon.ico
      '/robots.txt': public/robots.txt
      '/sitemap.xml': public/sitemap.xml
    domain: estcelafindelajournee.fr
    certificate: ${ssm:/estcelafindelajournee/certificatearn}

# Exclude files from deployment
package:
  exclude:
    - 'node_modules/**'
    - 'tests/**'
