service: estcelafindelajournee

provider:
  name: aws
  stage: prod
  region: eu-west-1
  environment:
    APP_ENV: 'prod'
    APP_DEBUG: false
    APP_SECRET: ${ssm:/estcelafindelajournee/secret}

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  api:
    handler: public/index.php
    description: 'estcelafindelajournee.fr'
    timeout: 10
    runtime: php-84-fpm
    events:
      - httpApi: '*'

constructs:
  website:
    type: server-side-website
    assets:
      '/assets/*': public/assets
      '/favicon.ico': public/favicon.ico
      '/robots.txt': public/robots.txt
      '/sitemap.xml': public/sitemap.xml
    domain: estcelafindelajournee.fr
    certificate: ${ssm:/estcelafindelajournee/certificatearn}

# Exclude files from deployment
package:
  patterns:
    - '!.env'
    - '!node_modules/**'
    - '!public/favicon.ico'
    - '!public/assets/**'
    - '!tests/**'
