name: Deploy to Prod

on:
  workflow_run:
    workflows:
      - "Run tests"
    types:
      - completed
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Remove useless folders and files
        run: |
          rm -rf .env
          rm -rf vendor/
          rm -rf bin/.phpunit
          rm -rf bin/phpunit
          rm -rf var/*

      - name: Install dependencies
        run: |
          composer self-update
          composer install --prefer-dist --optimize-autoloader --no-dev

      - name: Warmup cache
        run: php bin/console cache:warmup --env=prod

      - name: Install assets
        run: php bin/console assets:install --env prod

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-lift && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
