name: Deploy to Prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Remove useless folders and files
        run: |
          rm -rf .env
          rm -rf vendor/
          rm -rf bin/.phpunit
          rm -rf bin/phpunit
          rm -rf var/*

      - name: Install dependencies
        run: |
          composer self-update
          composer install --prefer-dist --optimize-autoloader --no-dev

      - name: Warmup cache
        run: php bin/console cache:warmup --env=prod

      - name: install serverless
        run: |
          npm install -g serverless
          npm install

      - name: Deploy to AWS
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
