name: Run tests

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
            -   uses: php-actions/composer@v6
            -   run: php bin/console cache:warmup --env=dev
            -   run: php bin/phpunit
            -   run: php vendor/bin/phpstan --error-format=github